services:
  - type: web
    name: client
    env: static
    buildCommand: npm install && npm run build
    staticPublishPath: dist   # or "build" if CRA
    routes:
      - type: rewrite
        source: /*
        destination: /index.html